plugins {
    id 'io.spring.dependency-management' version '1.1.7' apply false
    id 'co.uzzu.dotenv.gradle' version '4.0.0'
}

group = 'com.mariuszilinskas.streamix'
version = '1.0.1'

allprojects {
    group = rootProject.group
    version = rootProject.version

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'
    apply plugin: 'io.spring.dependency-management'
    apply plugin: 'jacoco'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
        withSourcesJar()
    }

    dependencyManagement {
        imports {
            mavenBom 'org.springframework.boot:spring-boot-dependencies:4.1.0'
        }
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                from components.java
            }
        }

        if (env.isPresent('CODE_ARTIFACT_URL') && env.isPresent('CODE_ARTIFACT_TOKEN')) {
            repositories {
                maven {
                    name = 'CodeArtifact'
                    url = uri(env.fetch('CODE_ARTIFACT_URL'))
                    credentials {
                        username = 'aws'
                        password = env.fetch('CODE_ARTIFACT_TOKEN')
                    }
                }
            }
        }
    }

    compileJava {
        options.compilerArgs << '-Xlint:deprecation'
    }

    compileTestJava {
        options.compilerArgs << '-Xlint:deprecation'
    }

    test {
        useJUnitPlatform()
        testLogging {
            events 'passed', 'skipped', 'failed'
        }
        finalizedBy jacocoTestReport
    }

    jacocoTestReport {
        dependsOn test
        reports {
            xml.required = true
            html.required = true
        }
    }
}